In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaboen as sns
from scipy import stats

In [2]:
df = pd.read_csv("E:/MyProjects/Unemployement in INDIA/india_unemployment_dataset_2020_2024_extended.csv")
df.head()

,Date,Year,Month,State,City,Metro City,Age Group,Education_Level,Family Background,Labour Force,Employed People,Unemployed People,Male Unemployed,Female Unemployed,Unemployement Rate,Urban Unemployement,Rural Unemployement,Youth Unemployement
0,2020-01,2020,Jan,Andhra Pradesh,Bangalore,Yes,45-54,Secondary School,Lower Middle,22158458,21138197,1020261,631426,388835,4.60,3.77,4.77,10.36
1,2020-02,2020,Feb,Andhra Pradesh,Mumbai,Yes,45-54,Primary School,Lower Middle,21929496,19455122,2474374,1729171,745203,11.28,10.30,9.35,15.38
2,2020-03,2020,Mar,Andhra Pradesh,Kolkata,Yes,45-54,Higher Secondary,Rich,24175300,22740166,1435134,839432,595702,5.94,6.34,6.52,10.66
3,2020-04,2020,Apr,Andhra Pradesh,Non-Metro,No,45-54,Postgraduate,Lower Middle,22967531,21413767,1553764,857661,696103,6.77,6.92,4.81,9.69
4,2020-05,2020,May,Andhra Pradesh,Kolkata,Yes,18-24,Higher Secondary,Lower Middle,23335679,21338522,1997157,1348039,649118,8.56,9.55,7.49,12.64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0    Date                 1680 non-null   object
 1   Year                  1680 non-null   int64
 2   Month                 1680 non-null   object
 3   State                 1680 non-null   object
 4   City                  1680 non-null   object
 5   Metro City            1680 non-null   object
 6   Age Group             1680 non-null   object
 7   Education_Level       1680 non-null   object
 8   Family Background     1680 non-null   object
 9   Labour Force          1680 non-null   int64
 10  Employed People       1680 non-null   int64
 11  Unemployed People     1680 non-null   int64
 12  Male Unemployed       1680 non-null   int64
 13  Female Unemployed     1680 non-null   int64
 14  Unemployement Rate    1680 non-null   float64
 15  Urban Unemployement   1680 non-null   float64
 16  Rural Unemployement   1680 non-null   float64
 17  Youth Unemployement   1680 non-null   float64
dtypes: float64(4), int64(6), object(8)
memory usage: 236.4+ KB

In [5]:
df.describe()

,Year,Labour Force,Employed People,Unemployed People,Male Unemployed,Female Unemployed,Unemployement Rate,Urban Unemployement,Rural Unemployement,Youth Unemployement
count,1680.000000,1.680000e+03,1.680000e+03,1.680000e+03,1.680000e+03,1.680000e+03,1680.000000,1680.000000,1680.000000,1680.000000
mean,2022.000000,2.444543e+07,2.274492e+07,1.700511e+06,1.061134e+06,6.393764e+05,6.958625,7.454381,6.444024,10.956196
std,1.414635,9.698302e+06,9.037900e+06,8.497523e+05,5.392225e+05,3.270235e+05,1.957235,2.140989,2.083226,2.291563
min,2020.000000,5.213065e+06,4.636071e+06,1.500170e+05,9.655900e+04,5.345800e+04,2.000000,1.000000,0.440000,4.070000
25%,2021.000000,1.667654e+07,1.558461e+07,1.014645e+06,6.346160e+05,3.802008e+05,5.650000,5.970000,5.030000,9.260000
50%,2022.000000,2.468557e+07,2.299032e+07,1.622436e+06,1.001732e+06,6.058200e+05,6.945000,7.445000,6.430000,11.005000
75%,2023.000000,3.163892e+07,2.948899e+07,2.271213e+06,1.418829e+06,8.606970e+05,8.340000,8.972500,7.910000,12.502500
max,2024.000000,4.184052e+07,3.977211e+07,4.853391e+06,3.004625e+06,1.916878e+06,12.940000,13.980000,13.100000,18.630000

In [6]:
df.shape

(1680, 18)

In [8]:
df.isnull().sum()

 Date                   0
Year                    0
Month                   0
State                   0
City                    0
Metro City              0
Age Group               0
Education_Level         0
Family Background       0
Labour Force            0
Employed People         0
Unemployed People       0
Male Unemployed         0
Female Unemployed       0
Unemployement Rate      0
Urban Unemployement     0
Rural Unemployement     0
Youth Unemployement     0
dtype: int64

In [10]:
df["City"] = df["City"].replace("Non-Metro", "Non Metro")
df

,Date,Year,Month,State,City,Metro City,Age Group,Education_Level,Family Background,Labour Force,Employed People,Unemployed People,Male Unemployed,Female Unemployed,Unemployement Rate,Urban Unemployement,Rural Unemployement,Youth Unemployement
0,2020-01,2020,Jan,Andhra Pradesh,Bangalore,Yes,45-54,Secondary School,Lower Middle,22158458,21138197,1020261,631426,388835,4.60,3.77,4.77,10.36
1,2020-02,2020,Feb,Andhra Pradesh,Mumbai,Yes,45-54,Primary School,Lower Middle,21929496,19455122,2474374,1729171,745203,11.28,10.30,9.35,15.38
2,2020-03,2020,Mar,Andhra Pradesh,Kolkata,Yes,45-54,Higher Secondary,Rich,24175300,22740166,1435134,839432,595702,5.94,6.34,6.52,10.66
3,2020-04,2020,Apr,Andhra Pradesh,Non Metro,No,45-54,Postgraduate,Lower Middle,22967531,21413767,1553764,857661,696103,6.77,6.92,4.81,9.69
4,2020-05,2020,May,Andhra Pradesh,Kolkata,Yes,18-24,Higher Secondary,Lower Middle,23335679,21338522,1997157,1348039,649118,8.56,9.55,7.49,12.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,2024-08,2024,Aug,West Bengal,Chennai,Yes,45-54,Postgraduate,Upper Middle,29076167,27574407,1501760,873609,628151,5.16,5.95,4.19,8.07
1676,2024-09,2024,Sep,West Bengal,Non Metro,No,45-54,Undergraduate,Rich,27605331,26033953,1571378,1003997,567381,5.69,7.22,3.99,11.67
1677,2024-10,2024,Oct,West Bengal,Pune,Yes,55-60,Primary School,Upper Middle,27605987,24502610,3103377,1782791,1320586,11.24,11.82,9.63,15.14
1678,2024-11,2024,Nov,West Bengal,Delhi,Yes,55-60,Higher Secondary,Lower Middle,26683331,25801536,881795,549129,332666,3.30,4.32,3.99,5.53
1679,2024-12,2024,Dec,West Bengal,Hyderabad,Yes,35-44,Higher Secondary,Lower Middle,28154136,25064741,3089395,1962868,1126527,10.97,11.80,9.55,14.07

In [11]:
df.to_csv("cleaned_unemployment_data.csv")